### ISSUE TITLE
Normalize IL to ensure consistent outcome.

### ISSUE THREAD

**Issue by tom-englert** [VerifyTests/Verify.ICSharpCode.Decompiler#388]
#### Is the feature request related to a problem

Tests occasionally break just because the layout has changed (class/member ordering), while the IL itself is still the same. 
see e.g. https://ci.appveyor.com/project/tom-englert/nullguard

see also https://github.com/icsharpcode/ILSpy/issues/2834

#### Describe the solution

Add option to sort IL output:
https://github.com/icsharpcode/ILSpy/pull/2835

either
- wait until new version of the de-compiler is available
- temporarily copy the source code changes of https://github.com/icsharpcode/ILSpy/pull/2835, so we can have an early release

#### Additional context

Should sorted output be the default (breaking change!) with the possibility to opt out, or better opt in (but you need to do it every time)

**Comment by tom-englert** [comment]
@SimonCropp please comment on the questions, I can then provide a PR.

**Comment by SimonCropp** [comment]
happy to accept a PR with this change. also happy to release a new major
