### ISSUE TITLE
It should not be necessary to call VerifyICSharpCodeDecompiler.Enable

### ISSUE THREAD

**Issue by tom-englert** [VerifyTests/Verify.ICSharpCode.Decompiler#400]
it should just work out of the box.

**Comment by SimonCropp** [comment]
this is problematic for a couple of reasons

 * it is desirable to be able to Verify ICSharpCode directly. ie i would prefer to have to remember to call `VerifyICSharpCodeDecompiler.Enable` once ather than remember that i always need to pass in a custom type that exists in Verify.ICSharpCode.Decompiler just to get the side effect of a hidden `VerifyICSharpCodeDecompiler.Enable`.
 * there is an ecosystem of extensions that all use the "enable in module init" pattern

**Comment by SimonCropp** [comment]
but `await Verify(new AssemblyToDisassemble(file))` requires people to always remember to use `AssemblyToDisassemble` every single time they verify an assembly. ie this wont work

```
using var file = new PEFile(assembly2Path);
await Verify(file);
```

**Comment by tom-englert** [comment]
So we make every days life harder, just to optimize one very rare edge case?

**Comment by SimonCropp** [comment]
"passing the actual type from the underlying library" is not a rare edge case. it is how the majority of verification happens

**Comment by SimonCropp** [comment]
currently undocumented, but u can call `VerifierSettings.InitializePlugins();` which will do a dll scan and call initialize on all verify plugins
